version: "3.8"
services:
  api_discovery_server:
    image: elleined/api-discovery-server:latest
    container_name: api_discovery_server
    networks:
      - api_discovery_server_network
    env_file:
      - .env
    ports:
      - "8761:8761"
networks:
  api_discovery_server_network:
    name: api_discovery_server_network
    external: false
    ipam:
      driver: default